import {useEffect,useMemo,useRef,useState} from 'react'
import {ArrowUpRight,BookOpen,BriefcaseBusiness,ChevronDown,Download,GraduationCap,Globe2,LayoutDashboard,LogOut,RefreshCw,Search,ShieldCheck,Sparkles,Users,X,FileText,Info} from 'lucide-react'
import {PieChart,Pie,Cell,ResponsiveContainer,Tooltip} from 'recharts'
import {getSupabase} from '@/lib/supabase'
import {useAuth} from '@/auth/authContext'
import {groups,fullNumber,compact,dateLabel,metricIndex,percentage,type PublishedReport,type DirectorReport} from './model'
const palette=['#3168ed','#12a893','#f3b44f','#8275dc','#d87a9a','#6398b1']
const icons=[LayoutDashboard,GraduationCap,BriefcaseBusiness,Users,Globe2,ShieldCheck,Sparkles,Users]
type Indexed = ReturnType<typeof metricIndex>
type Inspect = (ids:string[])=>void

function Bars({title,subtitle,rows,index,onInspect,series=['Ko‘rsatkich'],note}:{title:string;subtitle?:string;rows:{label:string;ids:string[]}[];index:Indexed;onInspect:Inspect;series?:string[];note?:string}){
 const [all,setAll]=useState(false)
 const [sort,setSort]=useState(false)
 const data=sort?[...rows].sort((a,b)=>(index[b.ids[0]]?.value??-1)-(index[a.ids[0]]?.value??-1)):rows
 const max=Math.max(1,...rows.flatMap(r=>r.ids.map(id=>index[id]?.value??0)))
 return <section className="bi-panel"><header><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button className="bi-text-button" aria-pressed={sort} onClick={()=>setSort(!sort)}>{sort?'Manba tartibi':'Saralash ↓'}</button></header>{series.length>1&&<div className="bi-legend">{series.map((s,i)=><span key={s}><i style={{background:palette[i]}}/>{s}</span>)}</div>}<div className="bi-bars">{(all?data:data.slice(0,7)).map(r=><button className="bi-bar-row" key={r.ids.join()} onClick={()=>onInspect(r.ids)}><span className="bi-bar-name">{r.label}</span><span className="bi-bar-tracks">{r.ids.map((id,i)=><span key={id} className="bi-track-line"><span className="bi-track"><span style={{width:`${(index[id]?.value??0)/max*100}%`,background:palette[i]}}/></span><b>{compact(index[id]?.value)}</b></span>)}</span></button>)}</div>{rows.length>7&&<button className="bi-text-button bi-expand" onClick={()=>setAll(!all)}>{all?'Qisqartirish':`Barchasi (${rows.length})`} <ChevronDown size={15}/></button>}{note&&<p className="bi-note"><Info size={15}/>{note}</p>}</section>
}
function Donut({title,ids,index,onInspect,note}:{title:string;ids:string[];index:Indexed;onInspect:Inspect;note?:string}){
 const data=ids.map((id,i)=>({id,name:index[id]?.label??id,value:index[id]?.value??0,color:({green:"#12a893",yellow:"#f3b44f",red:"#e77373"} as Record<string,string>)[id]??palette[i]}));const sum=data.reduce((n,r)=>n+r.value,0)
 const missing=ids.some(id=>index[id]?.value==null)
 return <section className="bi-panel"><header><h2>{title}</h2><span className="bi-unit">{index[ids[0]]?.unit}</span></header>{missing?<p className="bi-note">Ulushlarni ko‘rsatish uchun barcha qiymatlar kerak.</p>:<div className="bi-donut"><div className="bi-donut-chart"><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={data} dataKey="value" innerRadius={72} outerRadius={100} paddingAngle={3} stroke="none" onClick={(_,i)=>onInspect([data[i].id])}>{data.map(d=><Cell key={d.id} fill={d.color}/>)}</Pie><Tooltip formatter={v=>fullNumber(Number(v))}/></PieChart></ResponsiveContainer><div className="bi-donut-center"><b>{compact(sum)}</b><span>ko‘rsatilgan jami</span></div></div><div className="bi-donut-key">{data.map(d=><button key={d.id} onClick={()=>onInspect([d.id])}><i style={{background:d.color}}/><span>{d.name}<strong>{fullNumber(d.value)}</strong></span><b>{fullNumber(percentage(d.value,sum))}%</b></button>)}</div></div>}{note&&<p className="bi-note"><Info size={15}/>{note}</p>}</section>
}
function ProgressCard({title,numerator,denominator,index,onInspect}:{title:string;numerator:string;denominator:string;index:Indexed;onInspect:Inspect}){
 const n=index[numerator],d=index[denominator],pct=percentage(n?.value,d?.value)
 return <button className="bi-progress-card" onClick={()=>onInspect([numerator,denominator])}><span>{title}<ArrowUpRight size={18}/></span><strong>{fullNumber(pct)}{pct!==null?'%':''}</strong><div className="bi-progress-track"><i style={{width:`${Math.min(100,pct??0)}%`}}/></div><p>{fullNumber(n?.value)} / {fullNumber(d?.value)} {d?.unit}</p></button>
}
function exportCsv(report:DirectorReport,search:string,group:string){
 const clean=(x:unknown)=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"'
 const rows=[['Hisobot sanasi','Bo‘lim','Ko‘rsatkich','Qiymat','Birlik','Davr','Izoh','Manba']]
 for(const section of report.sections)for(const m of section.metrics){if(search ? !`${m.label} ${section.title}`.toLowerCase().includes(search.toLowerCase()) : group!=='overview'&&section.group!==group)continue;rows.push([report.asOf,section.title,m.label,m.value===null?'':String(m.value),m.unit,m.period,[section.note,m.note].filter(Boolean).join(' '),report.source+' · '+section.sourceSection])}
 const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(clean).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`yoshlar-${report.asOf}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
}
export function DashboardPage(){
 const {signOut}=useAuth();const [reports,setReports]=useState<PublishedReport[]>([]);const [selected,setSelected]=useState('');const [group,setGroup]=useState('overview');const [search,setSearch]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [reload,setReload]=useState(0);const [inspect,setInspect]=useState<string[]|null>(null);const [sourceOpen,setSourceOpen]=useState(false);const dialogRef=useRef<HTMLDialogElement>(null)
 useEffect(()=>{let cancelled=false,busy=false;const refresh=async()=>{if(busy)return;busy=true;try{const {data,error}=await getSupabase().rpc('read_dashboard_reports');if(cancelled)return;if(error){setError('Ma’lumotlarni yangilab bo‘lmadi. Qayta urinib ko‘ring.');if(error.code==='42501')setReports([])}else{setReports(data as unknown as PublishedReport[]);setError('')}}catch{if(!cancelled)setError('Internet aloqasini tekshiring.')}finally{busy=false;if(!cancelled)setLoading(false)}};void refresh();const timer=setInterval(refresh,60000);window.addEventListener('online',refresh);return()=>{cancelled=true;clearInterval(timer);window.removeEventListener('online',refresh)}},[reload])
 const current=reports.find(r=>r.id===selected)??reports[0];const report=current?.report;const index=useMemo(()=>report?metricIndex(report):{},[report]);
 useEffect(()=>{if(inspect||sourceOpen)dialogRef.current?.showModal();else dialogRef.current?.close()},[inspect,sourceOpen])
 const navigate=(id:string)=>{setGroup(id);setSearch('')};const onInspect:Inspect=ids=>setInspect(ids)
 if(loading)return <main className="bi-loading" role="status">Ko‘rsatkichlar yuklanmoqda…</main>
 if(!report)return <main className="bi-loading"><h1>{error||'Hali hisobot e’lon qilinmagan'}</h1><button onClick={()=>setReload(n=>n+1)}>Yangilash</button><button onClick={signOut}>Chiqish</button></main>
 const metrics=report.sections.flatMap(s=>s.metrics);const notes=report.sections.filter(s=>s.note).length;const rows=(ids:string[])=>ids.map(id=>({label:index[id]?.label??id,ids:[id]}));const prefix=(p:string)=>metrics.filter(m=>m.id.startsWith(p)).map(m=>m.id)
 const sections=report.sections.filter(s=>search?s.metrics.some(m=>`${m.label} ${s.title}`.toLowerCase().includes(search.toLowerCase())):group==='overview'||s.group===group)
 const value=(id:string)=>index[id]?.value
 return <main className="bi-app"><aside className="bi-sidebar"><div className="bi-logo"><span className="bi-mark">Y</span><div>Yoshlar ishlari<small>AGENTLIGI</small></div></div><div className="bi-nav-caption">TAHLILIY PANEL</div><nav aria-label="Dashboard bo‘limlari">{groups.map((g,i)=>{const Icon=icons[i];return <button key={g.id} className={group===g.id&&!search?'active':''} onClick={()=>navigate(g.id)}><Icon size={19}/>{g.label}</button>})}</nav><div className="bi-sidebar-bottom"><span className="bi-avatar">AS</span><div>Alisher Sa’dullayev<small>Rahbar</small></div><button aria-label="Chiqish" onClick={signOut}><LogOut size={18}/></button></div></aside><div className="bi-main"><header className="bi-topbar"><span>Respublika / <b>{groups.find(g=>g.id===group)?.label}</b></span><div><button className="bi-icon-button" aria-label="Yangilash" onClick={()=>setReload(n=>n+1)}><RefreshCw size={18}/></button><button className="bi-source-button" onClick={()=>setSourceOpen(true)}><FileText size={16}/>Manba</button><button className="bi-icon-button" aria-label="Hisobdan chiqish" onClick={signOut}><LogOut size={18}/></button></div></header><div className="bi-content"><div className="bi-page-heading"><div><p>YOSHLAR SIYOSATI · RESPUBLIKA</p><h1>{search?'Ko‘rsatkichlar qidiruvi':groups.find(g=>g.id===group)?.label}</h1><span>{dateLabel(report.asOf)} holatiga · {metrics.length} ko‘rsatkich</span></div><label className="bi-period">Hisobot sanasi<select aria-label="Hisobot sanasi" value={current.id} onChange={e=>{setSelected(e.target.value);setInspect(null)}}>{reports.map(r=><option value={r.id} key={r.id}>{dateLabel(r.report.asOf)}</option>)}</select></label></div><div className="bi-toolbar"><label className="bi-search"><Search size={18}/><input placeholder="Barcha ko‘rsatkichlardan qidirish…" aria-label="Ko‘rsatkich qidirish" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Qidiruvni tozalash" onClick={()=>setSearch('')}><X size={16}/></button>}</label><button className="bi-source-button" onClick={()=>exportCsv(report,search,group)}><Download size={16}/>CSV yuklab olish</button></div>{error&&<div className="bi-alert" role="alert">{error} Ko‘rsatilayotgan hisobot: {dateLabel(report.asOf)}.</div>}
 {!search&&group==='overview'&&<><div className="bi-kpis">{[{id:'population',title:'Respublika aholisi',caption:'Barcha yosh guruhlari',target:'overview'},{id:'youth14',title:'14–30 yoshdagi yoshlar',caption:`Aholining ${fullNumber(percentage(value('youth14'),value('population')))}%`,target:'overview'},{id:'employed_total',title:'Bandligi ta’minlangan',caption:`Ishsiz yoshlar balansining ${fullNumber(percentage(value('employed_total'),value('unemployed_total')))}%`,target:'employment'},{id:'crime26',title:'Yoshlar jinoyatlari',caption:`${index.crime26?.period??'Davr kiritilmagan'}`,target:'safety'}].map((k,i)=><button className={`bi-kpi bi-kpi-${i}`} key={k.id} onClick={()=>onInspect([k.id])}><span>{k.title}<ArrowUpRight size={17}/></span><strong>{compact(value(k.id))}</strong><small>{k.caption}</small><i/></button>)}</div><div className="bi-grid"><Bars title="Yosh guruhlari va qizlar soni" subtitle="Guruhlar bir-birini qamrab oladi · nafar" rows={['0','7','14','18'].map(age=>({label:age+'–30 yosh',ids:['youth'+age,'female'+age]}))} index={index} onInspect={onInspect} series={['Jami','Qizlar']}/><Donut title="Yoshlar balansi" ids={['green','yellow','red']} index={index} onInspect={onInspect} note={report.sections.find(s=>s.id==='balance')?.note}/></div><div className="bi-overview-links"><button onClick={()=>navigate('employment')}><BriefcaseBusiness/>Bandlik ijrosi<span>{fullNumber(percentage(value('employed_total'),value('unemployed_total')))}%</span><ArrowUpRight/></button><button onClick={()=>navigate('leaders')}><Users/>Yetakchilar vakansiyasi<span>{fullNumber(value('leaders_vacant'))}</span><ArrowUpRight/></button><button onClick={()=>setSourceOpen(true)}><Info/>Manba izohlari<span>{notes} bo‘lim</span><ArrowUpRight/></button></div><div className="bi-grid"><Bars title="Jinoyatlar: davrlar taqqoslovi" subtitle="Ta · davrlarni tekshirib taqqoslang" rows={[{label:'Yoshlar jinoyatlari',ids:['crime25','crime26']},{label:'Voyaga yetmaganlar',ids:['minor_crime25','minor_crime26']}]} index={index} onInspect={onInspect} series={[index.crime25?.period||'Oldingi davr',index.crime26?.period||'Keyingi davr']}/><Bars title="Rivojlanish loyihalari qamrovi" subtitle="Nafar · loyihalar qamrovi qo‘shilmaydi" rows={rows(['mutolaa','ibrat','ustoz','girls_academy'])} index={index} onInspect={onInspect}/></div></>}
 {!search&&group==='education'&&<><div className="bi-kpis">{['pre_children','school_students','voc_students','uni_students'].map(id=><button className="bi-kpi" key={id} onClick={()=>onInspect([id])}><span>{index[id]?.section}</span><strong>{compact(value(id))}</strong><small>{index[id]?.label} · nafar</small></button>)}</div><div className="bi-grid"><Bars title="Quvvat va qatnashuvchilar" subtitle="O‘rinlar va qatnashuvchilar soni" rows={[{label:'Maktabgacha ta’lim',ids:['pre_capacity','pre_children']},{label:'Maktablar',ids:['school_capacity','school_students']}]} index={index} onInspect={onInspect} series={['Quvvat','Qatnashuvchilar']}/><Bars title="Yoshlar infratuzilmasi" subtitle="Obyektlar soni · ta" rows={rows(report.sections.find(s=>s.id==='infrastructure')?.metrics.map(m=>m.id)??[])} index={index} onInspect={onInspect}/></div></>}
 {!search&&group==='employment'&&<><div className="bi-progress-grid"><ProgressCard title="Ishsiz yoshlar balansi ijrosi" numerator="employed_total" denominator="unemployed_total" index={index} onInspect={onInspect}/><ProgressCard title="Yer olganlar ichida undan foydalanayotganlar" numerator="land_using" denominator="land_youth" index={index} onInspect={onInspect}/></div><div className="bi-grid"><Bars title="Bandlik ta’minlangan yo‘nalishlar" subtitle="Nafar" rows={rows(prefix('job_'))} index={index} onInspect={onInspect}/><Bars title="Sariq toifa tarkibi" subtitle="Nafar · yoshlar balansi doirasida" rows={rows(prefix('yellow_'))} index={index} onInspect={onInspect} note={report.sections.find(s=>s.id==='yellow_detail')?.note}/><Bars title="Yashil toifa: asosiy yo‘nalishlar" subtitle="Nafar" rows={rows(['green_education','green_formal','green_business','green_farmers','green_self'])} index={index} onInspect={onInspect}/></div></>}
 {!search&&group==='support'&&<div className="bi-grid"><Donut title="Yoshlar daftariga murojaatlar" ids={['requests_approved','requests_rejected','requests_pending']} index={index} onInspect={onInspect}/><Bars title="Ijtimoiy yordam yo‘nalishlari" subtitle="Ko‘mak olganlar · nafar" rows={rows(prefix('help_'))} index={index} onInspect={onInspect}/><Bars title="Otaliqdagi yoshlar — idoralar kesimida" subtitle="Yoshlar soni · nafar" rows={rows(metrics.filter(m=>m.id.startsWith('mentor_')&&m.id.endsWith('_youth')&&m.id!=='mentor_youth').map(m=>m.id))} index={index} onInspect={onInspect} note={report.sections.find(s=>s.id==='mentoring')?.note}/><ProgressCard title="Yoshlar daftaridan chiqarilganlar" numerator="register_exited" denominator="register_entered" index={index} onInspect={onInspect}/></div>}
 {!search&&group==='migration'&&<><div className="bi-alert"><Info size={18}/>{report.sections.find(s=>s.id==='migration')?.note}</div><div className="bi-grid"><Bars title="Mehnat va ta’lim migratsiyasi" subtitle="Davlatlar kesimida · nafar" rows={prefix('work_').map(id=>({label:index[id].label.replace(' — mehnat',''),ids:[id,id.replace('work_','study_')]}))} series={['Mehnat','Ta’lim']} index={index} onInspect={onInspect} note={report.sections.find(s=>s.id==='countries')?.note}/><Bars title="Xorijda ta’lim olayotgan yoshlar" subtitle="Davlatlar kesimida · nafar" rows={rows(prefix('study_'))} index={index} onInspect={onInspect}/></div></>}
 {!search&&group==='safety'&&<div className="bi-grid"><Bars title="Jinoyatlar: davrlar taqqoslovi" subtitle="Ta" rows={[{label:'Yoshlar',ids:['crime25','crime26']},{label:'Voyaga yetmaganlar',ids:['minor_crime25','minor_crime26']}]} series={[index.crime25?.period||'Oldingi davr',index.crime26?.period||'Keyingi davr']} index={index} onInspect={onInspect}/><Bars title="Og‘ir toifa yo‘nalishlari" subtitle="Manbada keltirilgan toifalar · nafar" rows={rows(prefix('risk_'))} index={index} onInspect={onInspect}/><Bars title="Jinoyat sodir etgan shaxslar" subtitle="Nafar" rows={[{label:'Yoshlar',ids:['offenders25','offenders26']},{label:'Voyaga yetmaganlar',ids:['minor25','minor26']}]} series={[index.crime25?.period||'Oldingi davr',index.crime26?.period||'Keyingi davr']} index={index} onInspect={onInspect}/></div>}
 {!search&&group==='projects'&&<div className="bi-grid"><Bars title="Asosiy loyihalar qamrovi" subtitle="Nafar · bir shaxs bir nechta loyihada qatnashishi mumkin" rows={rows(['mutolaa','ibrat','ustoz','girls_academy'])} index={index} onInspect={onInspect}/><Bars title="Til o‘rganishni qo‘llab-quvvatlash" subtitle="Nafar · jami va yillik ko‘rsatkichlar alohida" rows={rows(['language_total','language_2026','two_six'])} index={index} onInspect={onInspect}/></div>}
 {!search&&group==='leaders'&&<><div className="bi-progress-grid"><ProgressCard title="Mahallalarda yetakchilar bilan ta’minlanish" numerator="leaders_active" denominator="leader_mahallas" index={index} onInspect={onInspect}/><button className="bi-progress-card" onClick={()=>onInspect(['leaders_vacant'])}><span>Vakant o‘rinlar<ArrowUpRight size={18}/></span><strong>{fullNumber(value('leaders_vacant'))}</strong><p>Mahalla yoshlar yetakchilari</p></button></div><div className="bi-grid"><Donut title="Mehnat staji" ids={['tenure1','tenure3','tenure5','tenure_more']} index={index} onInspect={onInspect}/><Bars title="Mutaxassislik yo‘nalishlari" subtitle="Nafar" rows={rows(prefix('spec_'))} index={index} onInspect={onInspect}/><Bars title="Faoliyat yuritish hududi" subtitle="Nafar" rows={rows(['leader_local','leader_district','leader_region','leader_otherregion'])} index={index} onInspect={onInspect}/><Bars title="Mukofot va sertifikatlar" subtitle="Har bir tur alohida; noyob shaxslar jami emas" rows={rows(['award_sign','award_future','award_glory','award_mahalla','cert_international','cert_national'])} index={index} onInspect={onInspect}/></div></>}
 <section className="bi-register"><div className="bi-register-heading"><div><h2>{search?'Qidiruv natijalari':'Ko‘rsatkichlar reyestri'}</h2><p>Qiymat, davr va manba tafsilotlarini ochish uchun qatorni tanlang.</p></div><BookOpen size={22}/></div>{!sections.length&&<p className="bi-empty">Mos ko‘rsatkich topilmadi.</p>}{sections.map(s=><details key={s.id} open={search?true:undefined}><summary><span>{s.title}<small>{s.metrics.length} ko‘rsatkich · {s.sourceSection}</small></span>{s.note&&<span className="bi-note-badge">Manba izohi</span>}<ChevronDown size={18}/></summary>{s.note&&<p className="bi-note"><Info size={15}/>{s.note}</p>}<div className="bi-table-scroll"><table><thead><tr><th>Ko‘rsatkich</th><th>Qiymat</th><th>Birlik</th><th>Davr</th></tr></thead><tbody>{s.metrics.filter(m=>!search||`${m.label} ${s.title}`.toLowerCase().includes(search.toLowerCase())).map(m=><tr key={m.id}><td><button onClick={()=>onInspect([m.id])}>{m.label}</button></td><td>{fullNumber(m.value)}</td><td>{m.unit}</td><td>{m.period}</td></tr>)}</tbody></table></div></details>)}</section><footer className="bi-footer"><span>{report.source} · {dateLabel(report.asOf)}</span><span>E’lon qilingan: {new Date(current.publishedAt).toLocaleString('uz-UZ',{timeZone:'Asia/Tashkent'})}</span></footer></div></div>
 <dialog ref={dialogRef} className="bi-dialog" onCancel={()=>{setInspect(null);setSourceOpen(false)}}><button className="bi-dialog-close" aria-label="Yopish" onClick={()=>{setInspect(null);setSourceOpen(false)}}><X/></button>{sourceOpen?<><small>MANBA VA DAVR</small><h2>{report.title}</h2><p>{report.source}</p><p>Ma’lumot sanasi: <b>{dateLabel(report.asOf)}</b></p><p>Hudud: Respublika. Ushbu hisobotda hududlar kesimi va oylik vaqt qatori berilmagan. Kelgusidagi hisobotlar sana tanlagichida paydo bo‘ladi.</p><h3>Manba izohlari</h3>{report.sections.filter(s=>s.note).map(s=><div key={s.id} className="bi-source-note"><strong>{s.title}</strong><p>{s.note}</p></div>)}{report.sourceText&&<details><summary>Hujjatdan olingan asl matn</summary><pre>{report.sourceText}</pre></details>}</>:<><small>KO‘RSATKICH TAFSILOTLARI</small>{inspect?.map(id=>{const m=index[id];return m?<section className="bi-metric-detail" key={id}><h2>{m.label}</h2><strong>{fullNumber(m.value)} <small>{m.unit}</small></strong><p>{m.section} · {m.period}</p><p>{m.note||'Qiymat manbada berilgan shaklda kiritilgan.'}</p>{m.sectionNote&&<p className="bi-note">{m.sectionNote}</p>}<p className="bi-detail-source">{report.source} · {m.sourceSection}</p></section>:null})}</>}</dialog></main>
}
